<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
<script type="text/javascript">
const paymentMethods = document.getElementsByName("payment[method]");
(paymentMethods).on('change', function () {
    if (paymentMethods.value != 'cointopayintlccgateway') {
        jQuery('#dt_method_cointopayintlccgateway').find('.cointopayintlcc-error').remove();
        jQuery('#payment-buttons-container').find('.button').show();
    }
});

// confirm order payment status
$(document).on('click', '#confirm_payments', function (event) {
    event.preventDefault();
    transaction_id = $('#cointopayintlcc_trid').val();
    $.ajax ({
        url: '<?php echo $this->getCoinsPaymentUrl() ?>',
        showLoader: true,
        data: {paymentaction:transaction_id, type:'status'},
        type: "POST",
        success: function(result) {
            var cointopay_response = JSON.parse(result);
            if (cointopay_response[1] == 'paid') {
                $('#cointointlcc_complete_order').show();
                $('#cointointlcc_complete_order')[0].click();
                $(".cointopayintlcc.popup-overlay, .cointopayintlcc.popup-content").removeClass("active");
                $(".cointopayintlcc-order").hide();
            } else if (cointopay_response[1] == 'waiting') {
                alert('Please double check you have successfully transfered payments.');
            } else if (cointopay_response[1] == 'expired') {
                alert('Sorry payment time expired now.');
                window.location.href = window.location.protocol + "//" + window.location.host + "/";
                return;
            }
        }
    });
});
setInterval(function() {
    if ($('#confirm_payments').length) {
        $('#confirm_payments')[0].click();
    }
}, 300000);
</script>